### ISSUE TITLE
Invlid URL Endpoint

### ISSUE THREAD

**Issue by Araon** [mainak17/spotify-etl#1]
https://github.com/mainak17/spotify-etl/blob/020a344fc74200cc94aac429cb7be6a9fbba03e8/main.py#L107

This is tested via 
curl --location 'https://api.spotify.com/v1/me/player/recently-played&before=1678991399000' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <token>'

response 
`{
    "error": {
        "status": 401,
        "message": "The access token expired"
    }
}`

Replacing `&`  with `?` works 

ref: [Spotify User Fetch](https://developer.spotify.com/console/get-current-user/)

**Comment by mainak17** [comment]
Resolved
